import type { Product } from "@/domain/products/model";

export const demoProducts: readonly Product[] = [
  {
    id: "demo-001",
    name: "Fone Essencial",
    slug: "fone-essencial",
    category: "Eletrônicos",
    type: "fisico",
    shortDescription: "Fone compacto para música, chamadas e rotina móvel.",
    description: "Produto fictício para demonstrar a experiência Orvani. Compare a oferta e confirme todos os detalhes diretamente na loja parceira.",
    currentPrice: 129.9,
    previousPrice: 179.9,
    currency: "BRL",
    primaryImage: "/images/demo/eletronicos.svg",
    images: ["/images/demo/eletronicos.svg"],
    partner: "shopee",
    affiliateUrl: "https://shopee.com.br",
    featured: true,
    active: true,
    stockStatus: "informativo",
    tags: ["áudio", "portátil", "rotina"],
    updatedAt: "2026-08-11T12:00:00.000Z",
  },
  {
    id: "demo-002",
    name: "Mochila Horizonte",
    slug: "mochila-horizonte",
    category: "Moda",
    type: "fisico",
    shortDescription: "Mochila urbana fictícia com organização para o dia a dia.",
    description: "Item demonstrativo com compartimentos versáteis e visual neutro. Especificações reais devem ser verificadas no destino.",
    currentPrice: 189.9,
    previousPrice: 239.9,
    currency: "BRL",
    primaryImage: "/images/demo/moda.svg",
    images: ["/images/demo/moda.svg"],
    partner: "amazon",
    affiliateUrl: "https://amazon.com.br",
    featured: true,
    active: true,
    stockStatus: "informativo",
    tags: ["urbano", "organização", "viagem"],
    updatedAt: "2026-08-10T15:00:00.000Z",
  },
  {
    id: "demo-003",
    name: "Jornada Nebulosa",
    slug: "jornada-nebulosa",
    category: "Jogos",
    type: "digital",
    shortDescription: "Jogo independente fictício de exploração e estratégia.",
    description: "Título demonstrativo criado para a Orvani, sem associação com publicadoras ou plataformas reais.",
    currentPrice: 49.9,
    previousPrice: 79.9,
    currency: "BRL",
    primaryImage: "/images/demo/games.svg",
    images: ["/images/demo/games.svg"],
    partner: "mercado_livre",
    affiliateUrl: "https://mercadolivre.com.br",
    featured: true,
    active: true,
    stockStatus: "disponivel",
    tags: ["aventura", "estratégia", "indie"],
    updatedAt: "2026-08-09T10:00:00.000Z",
  },
  {
    id: "demo-004",
    name: "App Foco Leve",
    slug: "app-foco-leve",
    category: "Aplicativos",
    type: "digital",
    shortDescription: "Aplicativo fictício para organizar sessões de concentração.",
    description: "Demonstração de um produto digital com recursos de listas e blocos de foco.",
    currentPrice: 24.9,
    previousPrice: null,
    currency: "BRL",
    primaryImage: "/images/demo/apps.svg",
    images: ["/images/demo/apps.svg"],
    partner: "amazon",
    affiliateUrl: "https://amazon.com.br",
    featured: false,
    active: true,
    stockStatus: "informativo",
    tags: ["produtividade", "foco", "digital"],
    updatedAt: "2026-08-11T09:30:00.000Z",
  },
  {
    id: "demo-005",
    name: "Clube de Leitura Aurora",
    slug: "clube-de-leitura-aurora",
    category: "Assinaturas",
    type: "digital",
    shortDescription: "Assinatura fictícia de leituras e encontros mensais.",
    description: "Serviço demonstrativo sem cobrança ou vínculo com uma empresa real.",
    currentPrice: 39.9,
    previousPrice: 49.9,
    currency: "BRL",
    primaryImage: "/images/demo/assinaturas.svg",
    images: ["/images/demo/assinaturas.svg"],
    partner: "shopee",
    affiliateUrl: "https://shopee.com.br",
    featured: false,
    active: true,
    stockStatus: "informativo",
    tags: ["leitura", "comunidade", "mensal"],
    updatedAt: "2026-08-08T13:00:00.000Z",
  },
  {
    id: "demo-006",
    name: "Luminária Orbital",
    slug: "luminaria-orbital",
    category: "Casa",
    type: "fisico",
    shortDescription: "Luminária de mesa fictícia com luz suave e ajustável.",
    description: "Objeto demonstrativo de iluminação para estudo e leitura.",
    currentPrice: 89.9,
    previousPrice: null,
    currency: "BRL",
    primaryImage: "/images/demo/casa.svg",
    images: ["/images/demo/casa.svg"],
    partner: "mercado_livre",
    affiliateUrl: "https://mercadolivre.com.br",
    featured: false,
    active: true,
    stockStatus: "informativo",
    tags: ["iluminação", "mesa", "leitura"],
    updatedAt: "2026-08-07T17:00:00.000Z",
  },
  {
    id: "demo-007",
    name: "Teclado Linha Clara",
    slug: "teclado-linha-clara",
    category: "Eletrônicos",
    type: "fisico",
    shortDescription: "Teclado compacto fictício para uma mesa organizada.",
    description: "Acessório demonstrativo com layout brasileiro e conexão sem fio fictícia.",
    currentPrice: 249.9,
    previousPrice: 299.9,
    currency: "BRL",
    primaryImage: "/images/demo/eletronicos.svg",
    images: ["/images/demo/eletronicos.svg"],
    partner: "amazon",
    affiliateUrl: "https://amazon.com.br",
    featured: true,
    active: true,
    stockStatus: "disponivel",
    tags: ["teclado", "escritório", "sem fio"],
    updatedAt: "2026-08-06T12:00:00.000Z",
  },
  {
    id: "demo-008",
    name: "Jaqueta Brisa",
    slug: "jaqueta-brisa",
    category: "Moda",
    type: "fisico",
    shortDescription: "Jaqueta leve fictícia para mudanças de temperatura.",
    description: "Peça demonstrativa em cor neutra, sem referência a fabricante real.",
    currentPrice: 219.9,
    previousPrice: null,
    currency: "BRL",
    primaryImage: "/images/demo/moda.svg",
    images: ["/images/demo/moda.svg"],
    partner: "shopee",
    affiliateUrl: "https://shopee.com.br",
    featured: false,
    active: true,
    stockStatus: "informativo",
    tags: ["casual", "leve", "unissex"],
    updatedAt: "2026-08-05T12:00:00.000Z",
  },
  {
    id: "demo-009",
    name: "Puzzle Prisma",
    slug: "puzzle-prisma",
    category: "Jogos",
    type: "fisico",
    shortDescription: "Quebra-cabeça geométrico fictício para todas as idades.",
    description: "Jogo demonstrativo de raciocínio com peças abstratas coloridas.",
    currentPrice: 69.9,
    previousPrice: 89.9,
    currency: "BRL",
    primaryImage: "/images/demo/games.svg",
    images: ["/images/demo/games.svg"],
    partner: "mercado_livre",
    affiliateUrl: "https://mercadolivre.com.br",
    featured: true,
    active: true,
    stockStatus: "informativo",
    tags: ["puzzle", "família", "geometria"],
    updatedAt: "2026-08-04T12:00:00.000Z",
  },
  {
    id: "demo-010",
    name: "Editor Notas Nuvem",
    slug: "editor-notas-nuvem",
    category: "Aplicativos",
    type: "digital",
    shortDescription: "Editor fictício para notas rápidas e referências.",
    description: "Software demonstrativo sem serviço real ou armazenamento externo.",
    currentPrice: 19.9,
    previousPrice: null,
    currency: "BRL",
    primaryImage: "/images/demo/apps.svg",
    images: ["/images/demo/apps.svg"],
    partner: "amazon",
    affiliateUrl: "https://amazon.com.br",
    featured: false,
    active: true,
    stockStatus: "disponivel",
    tags: ["notas", "organização", "digital"],
    updatedAt: "2026-08-03T12:00:00.000Z",
  },
  {
    id: "demo-011",
    name: "Estúdio Movimento",
    slug: "estudio-movimento",
    category: "Assinaturas",
    type: "digital",
    shortDescription: "Assinatura fictícia de aulas guiadas de mobilidade.",
    description: "Conteúdo demonstrativo, sem orientação médica ou vínculo com profissionais reais.",
    currentPrice: 59.9,
    previousPrice: 79.9,
    currency: "BRL",
    primaryImage: "/images/demo/assinaturas.svg",
    images: ["/images/demo/assinaturas.svg"],
    partner: "shopee",
    affiliateUrl: "https://shopee.com.br",
    featured: false,
    active: true,
    stockStatus: "informativo",
    tags: ["movimento", "bem-estar", "aulas"],
    updatedAt: "2026-08-02T12:00:00.000Z",
  },
  {
    id: "demo-012",
    name: "Organizador Arco",
    slug: "organizador-arco",
    category: "Casa",
    type: "fisico",
    shortDescription: "Organizador modular fictício para objetos cotidianos.",
    description: "Produto demonstrativo com formas simples e acabamento neutro.",
    currentPrice: 74.9,
    previousPrice: null,
    currency: "BRL",
    primaryImage: "/images/demo/casa.svg",
    images: ["/images/demo/casa.svg"],
    partner: "mercado_livre",
    affiliateUrl: "https://mercadolivre.com.br",
    featured: false,
    active: true,
    stockStatus: "informativo",
    tags: ["organização", "modular", "casa"],
    updatedAt: "2026-08-01T12:00:00.000Z",
  },
];
